services:
    app:
        container_name: d_form_app
        build:
            context: ./docker
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - ./bootstrap/cache:/app/bootstrap/cache:rw
            - ./storage:/app/storage:rw
            - caddy_data:/data
            - caddy_config:/config
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini # main config php
            - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini # config opcache
            - ./docker/caddy/Caddyfile:/etc/frankenphp/Caddyfile # config caddy
        networks:
            - default
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
            # - db
            # - redis
        restart: unless-stopped
        ports:
            - 80:8000
            - 443:443
            - 443:443/udp
        # command untuk development
        command: --watch

    db:
        container_name: d_form_db
        image: mysql:9.0
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - mysql_db:/var/lib/mysql
            - ./docker/mysql/healthcheck.cnf:/etc/mysql/healthcheck.cnf:ro
        ports:
            - ${DB_PORT}:3306
        networks:
            - default
        healthcheck:
            test: ['CMD', 'mysqladmin', '-p${DB_PASSWORD}', 'ping', '-h', 'localhost']
            timeout: 5s
            retries: 3

    redis:
        container_name: d_form_redis
        image: redis:8.0-alpine
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        restart: unless-stopped
        volumes:
            - redis_data:/data
        networks:
            - default
        command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
        healthcheck:
            test: ['CMD', 'redis-cli', '-a', '${REDIS_PASSWORD}', 'ping']
            timeout: 5s
            retries: 3

networks:
    default:
        driver: bridge

volumes:
    mysql_db:
        driver: local
    redis_data:
        driver: local
    caddy_data:
    caddy_config:
